[github]
repo_path = "alexfayers/computercraft_miner"
git_username = "alexfayers"
git_token_url = "http://192.168.1.54:8000/github.key"

[pastebin]
bootloader_template = "config/bootloader.lua.template"

[python]
interpreter_url = "http://192.168.1.54:8080/"
